FROM ubuntu:20.04
WORKDIR streaming_server
RUN apt update -y && apt install -y net-tools iputils-ping iproute2 ffmpeg vim python3
RUN apt install -y python3-pip && pip install ffmpeg-quality-metrics
COPY  MediaMtx .
COPY ./videos /videos
RUN chmod +x mediamtx
CMD  ["./mediamtx"]